---
name: Version checks

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - release/**
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  plugin:
    name: Plugin
    runs-on: ubuntu-latest
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 🚀 Check plugin release version
        run: >-
          python3 -m tools.check_release_version
          --branch "${GITHUB_HEAD_REF:-$GITHUB_REF_NAME}"
          --manifest custom_plugins/stream_overlays/manifest.json
